### PR TITLE
fix #650 OS_chmod uses read or write access.

### LINKED ISSUE #650: OS_chmod is requiring read access
**Describe the bug**
If you don't have read access to a file then OS_chmod will not be able to change it. This is most likely caused by chmod opening the file as a way to avoid filename race potential, see the code snip. 

**To Reproduce**
1) Set the file access to write only. 
2) Try to change the access using OS_chmod
3) will get an OS_ERROR

**Expected behavior**
You should be able to change the permissions of a file without read access. 

**Code snips**
https://github.com/nasa/osal/blob/1a826576f8dd9eb37f47da0e633b1d4712b8ac61/src/os/portable/os-impl-posix-files.c#L201-L206

**System observed on:**
 Ubuntu 20.04

**Reporter Info**
Alex Campbell GSFC

### PR DESCRIPTION
**Pull request by zanzaben**
**Describe the contribution**
Fixes #650 by checking for either read or write access instead of just read access 

**Testing performed**
Used the Chmod tests I am building in another branch that found this issue in the first place. 

**Expected behavior changes**
A clear and concise description of how this contribution will change behavior and level of impact.
-No changes 

**System(s) tested on**
Ubuntu 20.04

**Contributor Info - All information REQUIRED for consideration of pull request**
Alex Campbell GSFC

### CODE REVIEW

File: src/os/portable/os-impl-posix-files.c [hunk 1]
```diff
@@ -198,11 +198,15 @@ int32 OS_FileChmod_Impl(const char *local_path, uint32 access)
     struct stat st;
     int         fd;
 
-    /* Open file to avoid filename race potential */
+     /* Open file to avoid filename race potential */
```
Comment (skliper) [inline src/os/portable/os-impl-posix-files.c:201]: Errant whitespace change?

Comment (zanzaben) [reply src/os/portable/os-impl-posix-files.c:201]: looks like it, I will fix it when I get the inevitable conflict with #656

**Comment by astrogeco** [comment]
[CCB 20201202](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-December-02-2020) - APPROVED
