### PR TITLE
Fix #1083, timer reconfig tests

### LINKED ISSUE #1083: Timer "reconfig" tests do not work on RTEMS or VxWorks
**Describe the bug**
The "reconfig" tests were added to verify that timer config calls from the context of a timer callback are rejected. Unfortunately the underlying mechanism that allows this to happen only works on POSIX (via the pthread keys, which can do this).  On RTEMS and VxWorks, the mechanism which gets the task ID (`OS_TaskGetId_Impl`) doesn't return the timer ID when called from a timer task.

**To Reproduce**
Run timer tests on VxWorks or RTEMS, timer reconfig tests will fail.

**Expected behavior**
Test should pass.

**System observed on:**
MCP750 VxWorks 6.9
RTEMS 4.11.3

**Additional context**
Might be fixable on RTEMS but probably difficult to fix on VxWorks.  May want to consider just skipping this test?

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
The underlying OS mechanism that rejects calls to timer APIs from timer callbacks does not work on anything except POSIX.  This skips these unit tests on non-POSIX platforms, and also adds documentation clearly indicating that the API must not be called from a timer context.

Fixes #1083

**Testing performed**
Run unit tests

**Expected behavior changes**
Test now passes because this check is skipped on these platforms

**System(s) tested on**
MCP750 / VxWorks 6.9
QEMU / RTEMS 4.11

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

File: src/tests/time-base-api-test/time-base-api-test.c [hunk 1]
```diff
@@ -48,6 +48,7 @@ static uint32 UT_TimerSync(osal_id_t timer_id)
      * calls the various functions on the first time through and stores the
```
Comment (skliper) [inline src/tests/time-base-api-test/time-base-api-test.c:48]: Update comment - UtAssert not fully thread-safe OBE and add reasoning for non-POSIX exclusion

**Review by skliper — CHANGES_REQUESTED** [review]

**Review by pepepr08 — APPROVED** [review]

**Comment by astrogeco** [comment]
[CCB:2021-06-2021](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-June-30-2021) APPROVED

**Comment by astrogeco** [comment]
[CCB:2021-06-2021](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-June-30-2021) APPROVED

**Comment by jphickey** [comment]
Updated comment in commit 9a46055, should be OK to merge now.

File: src/tests/time-base-api-test/time-base-api-test.c (hunk 1 above)
Comment (jphickey) [reply src/tests/time-base-api-test/time-base-api-test.c]: Fixed in commit 9a46055d

**Comment by jphickey** [comment]
Updated again to include why only POSIX_OS is checked (missed that the first time).  Should be good now, for real.

**Comment by jphickey** [comment]
Commit a8db3cda only corrects whitespace for format check
