### PR TITLE
Fix #580, improve FS_BASED mounts on VxWorks

### LINKED ISSUE #580: Possible OSAL bug in OS_FileSysAddFixedMap not allowing FS_BASED mapping on VxWorks
**Describe the bug**
Unable to add a arbitrary filesystem path mappings with OS_FileSysAddFixedMap

**To Reproduce**
Call OS_FileSysAddFixedMap w/ parameters &fsid,"/", "/", and it'll fail

**Expected behavior**
Entry added to OS_filesys_table

**Code snips**
 It looks like the error code from line 516 is propagated improperly to line 530 instead of just being used to set flags on 524, causing the finalization step to fail. 
https://github.com/nasa/osal/blob/9c74b1b5207b0eb40662731eb205dba3014de5ed/src/os/shared/src/osapi-filesys.c#L511-L530

**System observed on:**
 - SP0-s
 - OS: VxWorks 6.9
 - CFE 6.7.0+dev292, OSAL 5.0.0+dev247, PSP 1.4.0+dev76 (w/ additions for SP0-s)

**Additional context**
Attempting to add a mapping to / for netbooting off of FTP on SP0-s PSP. Mapping /cf/ to /cf/ used to work earlier this year. In addition, OS_FileSys_FindVirtMountPoint appears to fail to map to "/" if it's in the table (although I suppose it's not desirable to map / in production anyway, since it'd override all other mappings). 

**Reporter Info**
John N Pham, Northrop Grumman

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
The mount/unmount implementation was not adequately checking for and handling the `FS_BASED` (pass -through) mapping type - which should be mostly a no-op.  But to be consistent with POSIX it should also create a mount point directory if it does not already exist when using this mapping type.

Adds a documentation note to `OS_FileSysAddFixedMap()` regarding the limitation that the virtual mount point cannot be empty - so `OS_FileSysAddFixedMap(.., "/", "/")` does not work - never did.  However `OS_FileSysAddFixedMap(.., "/", "/root")` does work and allows one to open files in the root as "/root/<file>" from OSAL applications.

Fixes #580

**Testing performed**
Build and run all unit tests on native
Sanity check CFE
Confirm behavior of `OS_FileSysAddFixedMap()` + `OS_TranslatePath()` when mapping to root FS.

**Expected behavior changes**
Mount point directories do not need to be already existing when using `OS_FileSysAddFixedMap`

**System(s) tested on**
Ubuntu 20.04 (native)
VxWorks 6.9 (mcp750)

**Additional context**
Auto-creating the mount point dir is relevant to unit tests - this simplifies running the unit tests by not requiring the user to pre-create this directory.  Otherwise without this one gets unit test failures if the directory doesn't already exist.

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by jphickey** [comment]
Ping @johnphamngc -- please review confirm if this is adequate to address the issue described in #580

**Review by skliper — APPROVED** [review]

File: src/os/vxworks/src/os-impl-filesys.c [hunk 1]
```diff
@@ -295,22 +296,62 @@ int32 OS_FileSysMountVolume_Impl(const OS_object_token_t *token)
...
+            }
+            else
+            {
+                OS_DEBUG("%s is not a directory\n", local->system_mountpt);
+                status = OS_FS_ERR_PATH_INVALID;
+            }
+        }
+        else
+        {
+            if (mkdir(local->system_mountpt, 0775) == 0)
```
Comment (johnphamngc) [inline src/os/vxworks/src/os-impl-filesys.c:327]: VxWorks mkdir doesn't take a mode; throws a lint error. 

https://docs.windriver.com/bundle/VxWorks_Kernel_API_Reference_6.9_1/page/1190833.html#b89517da-114c-41d9-a160-575213a358c5__mkdir

Comment (jphickey) [reply src/os/vxworks/src/os-impl-filesys.c:327]: Sorry - I should have mentioned, if you want to build you'll need to also pull the fix/workaround for VxWorks 7 compatibility in #706 (mkdir was fixed to be POSIX compliant in VxWorks 7).

**Comment by jphickey** [comment]
Added dependency label - if/when merging note that this also requires the compatibility fix in #706

File: src/os/vxworks/src/os-impl-filesys.c (hunk 1 above)
Comment (johnphamngc) [reply src/os/vxworks/src/os-impl-filesys.c:327]: Hm, this commit https://github.com/nasa/osal/commit/25cd5dfccfdb38ab879dd661d4fab42cce7f3a21 seems to have broken vxWorks when attempting to load cFE - "Warning: module 0x56d75b0 holds reference to undefined symbol OS_WaitForStateChange_Impl." when trying to build and run the branch. I'll see if I can backport the fix to OSAL 5.1.0-rc1+dev16 and see if it fixes the issue.

Comment (jphickey) [reply src/os/vxworks/src/os-impl-filesys.c:327]: Yeah there was a bunch of PRs recently, I thought #706 + this one would work in isolation but maybe not... 

At any rate, with this change I was able to test/confirm that you can do:

`OS_FileSysAddFixedMap(&fs_id, "/", "/root");`

Which succeeds, then followed by: 

`OS_TranslatePath("/root/myfile.txt", myfile_path)`

Which in turn sets `myfile_path` to `//myfile.txt` 

Note - yes it translates to a double leading slash but that is technically OK on UNIX and VxWorks seems to accept this and open it fine as well...

Comment (johnphamngc) [reply src/os/vxworks/src/os-impl-filesys.c:327]: Can you confirm that the case of `OS_FileSysAddFixedMap(&fs_id, "/cf", "/cf");` works as well? Otherwise I'll get around to backporting the fix and checking it sometime tomorrow. 

I think I'll make another ticket for the NFS directory case, since it's unrelated besides both affecting OS_FileSysMountVolume_Impl  and is a change in the POSIX OSAL instead. That one is a lower priority since I can just tell our developers to not run cFS off of an NFS mounted directory.

Comment (johnphamngc) [reply src/os/vxworks/src/os-impl-filesys.c:327]: Looks like it works for that case as well. I'll wait till we rebase w/ the latest CFE to see if the NFS issue manifests again before making another ticket.

Comment (jphickey) [reply src/os/vxworks/src/os-impl-filesys.c:327]: Thanks, and yes please submit a separate ticket for the NFS issue.  In the meantime I am looking into getting one of my test targets booted using an NFS root, and I'll check if anything looks amiss on it.

**Comment by astrogeco** [comment]
[CCB 2021-01-06](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-January-06-2021) APPROVED
