### PR TITLE
Fix #1356, Remove stray remaining 'goto' in OSAL test code

### LINKED ISSUE #1356: Stray remaining use of 'goto' in test code
**Describe the bug**
Noticed a single stray use of `goto` remaining in the test code.

**Expected behavior**
Use of `goto` is advised against by most coding guidelines.
Preference is to use other method of flow control.

**Code snips**
https://github.com/nasa/osal/blob/a9fece5f320617c850c5925c490ba31e916721b6/src/unit-tests/osfile-test/ut_osfile_test.c#L73-L94

**Reporter Info**
Avi Weiss @thnkslprpt

### PR DESCRIPTION
**Pull request by thnkslprpt**
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
- Fixes #1356 
  - 2 uses of `goto` are replaced with simple return statements.

**Testing performed**
GitHub CI actions (incl. Build + Run, Unit Tests etc.) all passing successfully.

**Expected behavior changes**
No change to logic.
Program flow is clearer, and removes the only remaining use of `goto` in OSAL.

**Contributor Info**
Avi Weiss @thnkslprpt

### CODE REVIEW

File: src/unit-tests/osfile-test/ut_osfile_test.c [hunk 1]
```diff
@@ -78,18 +78,17 @@ int32 UT_os_setup_fs()
...
     if (res != OS_SUCCESS)
     {
         UtPrintf("OS_mount() returns %d\n", (int)res);
         OS_rmfs(g_devName);
-        goto UT_os_setup_fs_exit_tag;
+        return res;
     }
 
-UT_os_setup_fs_exit_tag:
     return res;
```
Comment (skliper) [inline src/unit-tests/osfile-test/ut_osfile_test.c:92]: Multiple returns should be avoided.  Consider and if/else and remove the second return:
```
if
{
  print
}
else
{
  mount
  if
  {
     print and rmfs
  }
}
return res
```

**Review by skliper — APPROVED** [review]

**Review by jphickey — APPROVED** [review]
